import { Booking, Product, Review, User } from "../types/product.types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "https://i.pravatar.cc/150?u=1",
    rating: 4.8,
    memberSince: "2023-01-15",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "https://i.pravatar.cc/150?u=2",
    rating: 4.9,
    memberSince: "2023-03-20",
  },
];

export const mockProducts: Product[] = [
  // Existing products (keep as is or modify for Bangladesh context)
  {
    id: "1",
    title: "Sony A7III Camera",
    description:
      "Professional mirrorless camera in excellent condition. Includes kit lens and battery.",
    price: 2000,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400",
    ],
    category: "Cameras",
    owner: mockUsers[0],
    location: "Gulshan, Dhaka",
    rating: 4.9,
    reviewsCount: 24,
    available: true,
    specs: {
      brand: "Sony",
      model: "A7III",
      condition: "Like New",
    },
    createdAt: "2024-01-10",
  },
  {
    id: "2",
    title: 'MacBook Pro 14"',
    description: "2023 model with M2 Pro chip, 16GB RAM, 512GB SSD",
    price: 3000,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
    ],
    category: "Electronics",
    owner: mockUsers[1],
    location: "Banani, Dhaka",
    rating: 4.8,
    reviewsCount: 18,
    available: true,
    specs: {
      brand: "Apple",
      model: "MacBook Pro 14",
      condition: "Excellent",
    },
    createdAt: "2024-01-15",
  },
  {
    id: "3",
    title: "Electric Drill Set",
    description:
      "Professional grade drill set with multiple bits and accessories",
    price: 500,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400",
    ],
    category: "Tools",
    owner: mockUsers[0],
    location: "Dhanmondi, Dhaka",
    rating: 4.7,
    reviewsCount: 12,
    available: true,
    specs: {
      brand: "DeWalt",
      condition: "Good",
    },
    createdAt: "2024-01-20",
  },
  // New Bangladeshi context products
  {
    id: "4",
    title: "Canon EOS 200D Camera",
    description:
      "DSLR camera with 18-55mm lens, perfect for photography enthusiasts",
    price: 1500,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400",
    ],
    category: "Cameras",
    owner: mockUsers[1],
    location: "Uttara, Dhaka",
    rating: 4.6,
    reviewsCount: 15,
    available: true,
    specs: {
      brand: "Canon",
      model: "EOS 200D",
      condition: "Good",
    },
    createdAt: "2024-02-01",
  },
  {
    id: "5",
    title: "PlayStation 5",
    description: "Latest PS5 with 2 controllers and 3 games included",
    price: 800,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400",
    ],
    category: "Electronics",
    owner: mockUsers[0],
    location: "Bashundhara, Dhaka",
    rating: 5.0,
    reviewsCount: 8,
    available: true,
    specs: {
      brand: "Sony",
      model: "PS5",
      condition: "Like New",
    },
    createdAt: "2024-02-05",
  },
  {
    id: "6",
    title: "Wedding Photography Gear Set",
    description:
      "Complete setup: Sony A7III, 24-70mm lens, 70-200mm lens, flash, and tripod",
    price: 5000,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=400",
    ],
    category: "Cameras",
    owner: mockUsers[1],
    location: "Mohakhali, Dhaka",
    rating: 4.9,
    reviewsCount: 32,
    available: true,
    specs: {
      brand: "Sony",
      condition: "Excellent",
    },
    createdAt: "2024-02-10",
  },
  {
    id: "7",
    title: "DJI Mavic Air 2 Drone",
    description: "4K drone with 3 batteries and carrying case",
    price: 2500,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1579822510799-5d241f0b43e8?w=400",
    ],
    category: "Electronics",
    owner: mockUsers[0],
    location: "Gulshan, Dhaka",
    rating: 4.8,
    reviewsCount: 11,
    available: true,
    specs: {
      brand: "DJI",
      model: "Mavic Air 2",
      condition: "Excellent",
    },
    createdAt: "2024-02-12",
  },
  {
    id: "8",
    title: "Modern L-Shaped Sofa",
    description: "Comfortable fabric sofa, perfect for apartment living room",
    price: 800,
    priceUnit: "day",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400"],
    category: "Furniture",
    owner: mockUsers[1],
    location: "Banani, Dhaka",
    rating: 4.5,
    reviewsCount: 6,
    available: true,
    specs: {
      brand: "Hatil",
      condition: "Good",
    },
    createdAt: "2024-02-15",
  },
  {
    id: "9",
    title: "Professional Carpentry Tool Set",
    description:
      "Complete set including saws, hammers, measuring tools, and power tools",
    price: 800,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=400",
    ],
    category: "Tools",
    owner: mockUsers[0],
    location: "Mirpur, Dhaka",
    rating: 4.7,
    reviewsCount: 9,
    available: true,
    specs: {
      brand: "Stanley",
      condition: "Good",
    },
    createdAt: "2024-02-18",
  },
  {
    id: "10",
    title: "Football Set (Size 5)",
    description: "Professional football with pump and cones for training",
    price: 200,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1575361204480-a3d5b354a50c?w=400",
    ],
    category: "Sports",
    owner: mockUsers[1],
    location: "Mohammadpur, Dhaka",
    rating: 4.6,
    reviewsCount: 14,
    available: true,
    specs: {
      brand: "Adidas",
      condition: "Good",
    },
    createdAt: "2024-02-20",
  },
  {
    id: "11",
    title: "Complete Cricket Kit",
    description:
      "Bat, pads, helmet, gloves, and balls - everything for a cricket match",
    price: 600,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=400",
    ],
    category: "Sports",
    owner: mockUsers[1],
    location: "Sylhet",
    rating: 4.9,
    reviewsCount: 21,
    available: true,
    specs: {
      brand: "SG",
      condition: "Excellent",
    },
    createdAt: "2024-02-22",
  },
  {
    id: "12",
    title: "Library of Academic Books",
    description: "Collection of 50+ engineering reference books",
    price: 300,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400",
    ],
    category: "Books",
    owner: mockUsers[0],
    location: "Farmgate, Dhaka",
    rating: 4.4,
    reviewsCount: 7,
    available: true,
    specs: {
      condition: "Good",
    },
    createdAt: "2024-02-25",
  },
  {
    id: "13",
    title: "Yoga Mat Set",
    description: "Premium yoga mat with blocks and straps",
    price: 150,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400",
    ],
    category: "Sports",
    owner: mockUsers[1],
    location: "Uttara, Dhaka",
    rating: 4.7,
    reviewsCount: 13,
    available: true,
    specs: {
      brand: "Lululemon",
      condition: "Like New",
    },
    createdAt: "2024-02-27",
  },
  {
    id: "14",
    title: "6-Seater Dining Table Set",
    description: "Modern wooden dining table with 6 chairs",
    price: 600,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=400",
    ],
    category: "Furniture",
    owner: mockUsers[1],
    location: "Chittagong",
    rating: 4.5,
    reviewsCount: 5,
    available: true,
    specs: {
      brand: "Otobi",
      condition: "Good",
    },
    createdAt: "2024-02-28",
  },
  {
    id: "15",
    title: "iPad Pro 12.9",
    description: "M1 chip, 256GB, with Apple Pencil 2nd gen",
    price: 1200,
    priceUnit: "day",
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400"],
    category: "Electronics",
    owner: mockUsers[0],
    location: "Gulshan, Dhaka",
    rating: 4.9,
    reviewsCount: 16,
    available: true,
    specs: {
      brand: "Apple",
      model: "iPad Pro",
      condition: "Like New",
    },
    createdAt: "2024-03-01",
  },
  {
    id: "16",
    title: "Blyton Children's Books Collection",
    description: "20 Enid Blyton books for kids",
    price: 200,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    ],
    category: "Books",
    owner: mockUsers[1],
    location: "Dhanmondi, Dhaka",
    rating: 4.8,
    reviewsCount: 19,
    available: true,
    specs: {
      condition: "Good",
    },
    createdAt: "2024-03-02",
  },
  {
    id: "17",
    title: "Professional Generator 3kVA",
    description: "Silent generator for events and construction",
    price: 1500,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400",
    ],
    category: "Tools",
    owner: mockUsers[1],
    location: "Tejgaon, Dhaka",
    rating: 4.6,
    reviewsCount: 8,
    available: true,
    specs: {
      brand: "Honda",
      condition: "Excellent",
    },
    createdAt: "2024-03-03",
  },
  {
    id: "18",
    title: "Wedding Decoration Package",
    description:
      "Complete decoration set including lights, flowers, and backdrop",
    price: 5000,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=400",
    ],
    category: "Tools",
    owner: mockUsers[1],
    location: "Baridhara, Dhaka",
    rating: 4.9,
    reviewsCount: 27,
    available: true,
    specs: {
      condition: "Good",
    },
    createdAt: "2024-03-04",
  },
  {
    id: "19",
    title: "Tent and Camping Gear",
    description: "4-person tent, sleeping bags, and cooking equipment",
    price: 800,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400",
    ],
    category: "Sports",
    owner: mockUsers[1],
    location: "Bandarban",
    rating: 4.7,
    reviewsCount: 12,
    available: true,
    specs: {
      brand: "Quechua",
      condition: "Good",
    },
    createdAt: "2024-03-05",
  },
  {
    id: "20",
    title: "Kitchen Appliance Set",
    description: "Mixer grinder, oven, rice cooker, and blender",
    price: 400,
    priceUnit: "day",
    images: ["https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400"],
    category: "Electronics",
    owner: mockUsers[1],
    location: "Khulna",
    rating: 4.5,
    reviewsCount: 9,
    available: true,
    specs: {
      brand: "Panasonic",
      condition: "Good",
    },
    createdAt: "2024-03-06",
  },
  {
    id: "21",
    title: "Office Desk and Chair Set",
    description: "Ergonomic office furniture set",
    price: 350,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=400",
    ],
    category: "Furniture",
    owner: mockUsers[1],
    location: "Motijheel, Dhaka",
    rating: 4.6,
    reviewsCount: 7,
    available: true,
    specs: {
      brand: "Hatil",
      condition: "Good",
    },
    createdAt: "2024-03-07",
  },
  {
    id: "22",
    title: "Gaming Chair",
    description: "RGB gaming chair with lumbar support",
    price: 400,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=400",
    ],
    category: "Furniture",
    owner: mockUsers[1],
    location: "Bashundhara, Dhaka",
    rating: 4.8,
    reviewsCount: 14,
    available: true,
    specs: {
      brand: "Razer",
      condition: "Excellent",
    },
    createdAt: "2024-03-08",
  },
  {
    id: "23",
    title: "Badminton Set",
    description: "Professional rackets, shuttlecocks, and net",
    price: 200,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400",
    ],
    category: "Sports",
    owner: mockUsers[0],
    location: "Rajshahi",
    rating: 4.7,
    reviewsCount: 16,
    available: true,
    specs: {
      brand: "Yonex",
      condition: "Good",
    },
    createdAt: "2024-03-09",
  },
  {
    id: "24",
    title: "Islamic Books Collection",
    description: "50+ Islamic books including Quran translations and Hadith",
    price: 250,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1589187151053-5ec88152e1c6?w=400",
    ],
    category: "Books",
    owner: mockUsers[1],
    location: "Moghbazar, Dhaka",
    rating: 4.9,
    reviewsCount: 23,
    available: true,
    specs: {
      condition: "Excellent",
    },
    createdAt: "2024-03-10",
  },
  {
    id: "25",
    title: "PA System and Speakers",
    description: "Complete sound system for events with microphones",
    price: 2000,
    priceUnit: "day",
    images: ["https://images.unsplash.com/photo-1545454677-353c1e8c8f5a?w=400"],
    category: "Electronics",
    owner: mockUsers[1],
    location: "Farmgate, Dhaka",
    rating: 4.8,
    reviewsCount: 18,
    available: true,
    specs: {
      brand: "Yamaha",
      condition: "Good",
    },
    createdAt: "2024-03-11",
  },
  {
    id: "26",
    title: "Baby Furniture Set",
    description: "Crib, changing table, and rocking chair",
    price: 500,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1592664475318-d0cb2de26492?w=400",
    ],
    category: "Furniture",
    owner: mockUsers[0],
    location: "Uttara, Dhaka",
    rating: 4.7,
    reviewsCount: 11,
    available: true,
    specs: {
      brand: "Partex",
      condition: "Good",
    },
    createdAt: "2024-03-12",
  },
  {
    id: "27",
    title: "Professional Painting Tools",
    description: "Spray gun, brushes, rollers, and paint trays",
    price: 500,
    priceUnit: "day",
    images: ["https://images.unsplash.com/photo-1562259929-b4ec1f94f7d1?w=400"],
    category: "Tools",
    owner: mockUsers[1],
    location: "Mirpur, Dhaka",
    rating: 4.6,
    reviewsCount: 8,
    available: true,
    specs: {
      brand: "Bosch",
      condition: "Good",
    },
    createdAt: "2024-03-13",
  },
  {
    id: "28",
    title: "GoPro Hero 11",
    description: "Action camera with waterproof case and accessories",
    price: 800,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1584441405886-bc91be61e56a?w=400",
    ],
    category: "Cameras",
    owner: mockUsers[0],
    location: "Chittagong",
    rating: 4.9,
    reviewsCount: 15,
    available: true,
    specs: {
      brand: "GoPro",
      model: "Hero 11",
      condition: "Like New",
    },
    createdAt: "2024-03-14",
  },
  {
    id: "29",
    title: "HUMAX TV 55 inch",
    description: "4K UHD Smart TV with Netflix and YouTube",
    price: 800,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400",
    ],
    category: "Electronics",
    owner: mockUsers[1],
    location: "Bogra",
    rating: 4.7,
    reviewsCount: 9,
    available: true,
    specs: {
      brand: "Samsung",
      model: "55 inch",
      condition: "Excellent",
    },
    createdAt: "2024-03-15",
  },
  {
    id: "30",
    title: "Mehendi Decoration Set",
    description:
      "Traditional wedding decoration items including lights and drapes",
    price: 1000,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?w=400",
    ],
    category: "Tools",
    owner: mockUsers[0],
    location: "Old Dhaka",
    rating: 4.8,
    reviewsCount: 22,
    available: true,
    specs: {
      condition: "Good",
    },
    createdAt: "2024-03-16",
  },
  {
    id: "31",
    title: "Bicycle (Mountain Bike)",
    description: "21-gear mountain bike, perfect for riding in the city",
    price: 300,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=400",
    ],
    category: "Sports",
    owner: mockUsers[1],
    location: "Gazipur",
    rating: 4.6,
    reviewsCount: 13,
    available: true,
    specs: {
      brand: "Duranta",
      condition: "Good",
    },
    createdAt: "2024-03-17",
  },
  {
    id: "32",
    title: "Academic Textbooks Bundle",
    description: "MBA reference books and study materials",
    price: 400,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400",
    ],
    category: "Books",
    owner: mockUsers[0],
    location: "Niketan, Dhaka",
    rating: 4.5,
    reviewsCount: 7,
    available: true,
    specs: {
      condition: "Good",
    },
    createdAt: "2024-03-18",
  },
  {
    id: "33",
    title: "Children's Playhouse",
    description: "Plastic playhouse with slide and ball pit",
    price: 600,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400",
    ],
    category: "Furniture",
    owner: mockUsers[0],
    location: "Baridhara, Dhaka",
    rating: 4.8,
    reviewsCount: 10,
    available: true,
    specs: {
      brand: "Step2",
      condition: "Excellent",
    },
    createdAt: "2024-03-19",
  },
  {
    id: "34",
    title: "Photography Lighting Kit",
    description: "2 softboxes, 2 stands, and backdrop set",
    price: 700,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400",
    ],
    category: "Cameras",
    owner: mockUsers[1],
    location: "Gulshan, Dhaka",
    rating: 4.7,
    reviewsCount: 14,
    available: true,
    specs: {
      brand: "Godox",
      condition: "Good",
    },
    createdAt: "2024-03-20",
  },
  {
    id: "35",
    title: "Lawn Mower and Garden Tools",
    description: "Electric lawn mower with trimmer and gardening tools",
    price: 600,
    priceUnit: "day",
    images: ["https://images.unsplash.com/photo-1557429287-b2e26467fc2b?w=400"],
    category: "Tools",
    owner: mockUsers[0],
    location: "Savar, Dhaka",
    rating: 4.6,
    reviewsCount: 6,
    available: true,
    specs: {
      brand: "Black+Decker",
      condition: "Good",
    },
    createdAt: "2024-03-21",
  },
  {
    id: "36",
    title: "Projector and Screen",
    description: "Full HD projector with 100-inch screen for movie nights",
    price: 1000,
    priceUnit: "day",
    images: [
      "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=400",
    ],
    category: "Electronics",
    owner: mockUsers[0],
    location: "Banani, Dhaka",
    rating: 4.9,
    reviewsCount: 19,
    available: true,
    specs: {
      brand: "Epson",
      condition: "Excellent",
    },
    createdAt: "2024-03-22",
  },
];
export const mockReviews: Review[] = [
  // Product 1 - Camera
  {
    id: "1",
    productId: "1",
    userId: "2",
    userName: "Jane Smith",
    userAvatar: "https://i.pravatar.cc/150?u=2",
    rating: 5,
    comment: "Great camera, worked perfectly for my photoshoot!",
    date: "2024-01-25",
  },
  {
    id: "2",
    productId: "1",
    userId: "1",
    userName: "John Doe",
    userAvatar: "https://i.pravatar.cc/150?u=1",
    rating: 4,
    comment: "Good condition, owner was helpful.",
    date: "2024-01-20",
  },
  {
    id: "3",
    productId: "1",
    userId: "3",
    userName: "Mike Johnson",
    userAvatar: "https://i.pravatar.cc/150?u=3",
    rating: 5,
    comment: "Amazing camera! Captured some incredible shots.",
    date: "2024-01-15",
  },

  // Product 2 - Laptop
  {
    id: "4",
    productId: "2",
    userId: "4",
    userName: "Sarah Wilson",
    userAvatar: "https://i.pravatar.cc/150?u=4",
    rating: 5,
    comment: "Perfect for my work from home setup. Fast and reliable.",
    date: "2024-01-28",
  },
  {
    id: "5",
    productId: "2",
    userId: "5",
    userName: "David Brown",
    userAvatar: "https://i.pravatar.cc/150?u=5",
    rating: 4,
    comment: "Great laptop, battery life was impressive.",
    date: "2024-01-22",
  },

  // Product 3 - Drill
  {
    id: "6",
    productId: "3",
    userId: "6",
    userName: "Tom Harris",
    userAvatar: "https://i.pravatar.cc/150?u=6",
    rating: 5,
    comment: "Powerful drill, made my DIY project so easy!",
    date: "2024-01-27",
  },
  {
    id: "7",
    productId: "3",
    userId: "7",
    userName: "Lisa Anderson",
    userAvatar: "https://i.pravatar.cc/150?u=7",
    rating: 4,
    comment: "Good condition, came with all the bits I needed.",
    date: "2024-01-19",
  },

  // Product 4 - Tent
  {
    id: "8",
    productId: "4",
    userId: "8",
    userName: "Chris Lee",
    userAvatar: "https://i.pravatar.cc/150?u=8",
    rating: 5,
    comment: "Perfect weekend camping trip! Tent was in excellent condition.",
    date: "2024-01-26",
  },
  {
    id: "9",
    productId: "4",
    userId: "9",
    userName: "Emma Davis",
    userAvatar: "https://i.pravatar.cc/150?u=9",
    rating: 5,
    comment: "Easy to set up and waterproof. Highly recommend!",
    date: "2024-01-18",
  },

  // Product 5 - Books
  {
    id: "10",
    productId: "5",
    userId: "10",
    userName: "Alex Turner",
    userAvatar: "https://i.pravatar.cc/150?u=10",
    rating: 4,
    comment: "Great collection, books were in good condition.",
    date: "2024-01-24",
  },
  {
    id: "11",
    productId: "5",
    userId: "11",
    userName: "Rachel Green",
    userAvatar: "https://i.pravatar.cc/150?u=11",
    rating: 5,
    comment: "Loved reading these! The owner was very kind.",
    date: "2024-01-16",
  },

  // Product 6 - Bike
  {
    id: "12",
    productId: "6",
    userId: "12",
    userName: "Peter Parker",
    userAvatar: "https://i.pravatar.cc/150?u=12",
    rating: 5,
    comment: "Smooth ride, gears work perfectly. Great for city commuting.",
    date: "2024-01-29",
  },
  {
    id: "13",
    productId: "6",
    userId: "13",
    userName: "Mary Jane",
    userAvatar: "https://i.pravatar.cc/150?u=13",
    rating: 4,
    comment: "Good bike, comfortable seat. Would rent again.",
    date: "2024-01-21",
  },

  // Product 7 - Projector
  {
    id: "14",
    productId: "7",
    userId: "14",
    userName: "Tony Stark",
    userAvatar: "https://i.pravatar.cc/150?u=14",
    rating: 5,
    comment: "Movie night was a success! Great picture quality.",
    date: "2024-01-23",
  },
  {
    id: "15",
    productId: "7",
    userId: "15",
    userName: "Pepper Potts",
    userAvatar: "https://i.pravatar.cc/150?u=15",
    rating: 5,
    comment: "Perfect for presentations and movies. Very clear.",
    date: "2024-01-17",
  },

  // Product 8 - Suitcase
  {
    id: "16",
    productId: "8",
    userId: "16",
    userName: "Bruce Wayne",
    userAvatar: "https://i.pravatar.cc/150?u=16",
    rating: 4,
    comment: "Spacious and durable. Wheels roll smoothly.",
    date: "2024-01-28",
  },
  {
    id: "17",
    productId: "8",
    userId: "17",
    userName: "Clark Kent",
    userAvatar: "https://i.pravatar.cc/150?u=17",
    rating: 5,
    comment: "Perfect for my weekend trip. Highly recommend!",
    date: "2024-01-14",
  },

  // Product 9 - Guitar
  {
    id: "18",
    productId: "9",
    userId: "18",
    userName: "Jimmy Page",
    userAvatar: "https://i.pravatar.cc/150?u=18",
    rating: 5,
    comment: "Beautiful sound, well maintained. Great for practice.",
    date: "2024-01-26",
  },
  {
    id: "19",
    productId: "9",
    userId: "19",
    userName: "Eric Clapton",
    userAvatar: "https://i.pravatar.cc/150?u=19",
    rating: 4,
    comment: "Good guitar, strings were recently changed.",
    date: "2024-01-19",
  },

  // Product 10 - Drone
  {
    id: "20",
    productId: "10",
    userId: "20",
    userName: "Luke Skywalker",
    userAvatar: "https://i.pravatar.cc/150?u=20",
    rating: 5,
    comment: "Incredible drone! Stable flight and amazing camera.",
    date: "2024-01-27",
  },
  {
    id: "21",
    productId: "10",
    userId: "21",
    userName: "Han Solo",
    userAvatar: "https://i.pravatar.cc/150?u=21",
    rating: 5,
    comment: "Flew like a dream. Easy to control for beginners.",
    date: "2024-01-20",
  },
];

export const mockBookings: Booking[] = [
  // Product 1 - Camera bookings
  {
    id: "1",
    productId: "1",
    userId: "2",
    startDate: "2024-02-01",
    endDate: "2024-02-05",
    totalPrice: 200,
    status: "confirmed",
  },
  {
    id: "2",
    productId: "1",
    userId: "3",
    startDate: "2024-02-10",
    endDate: "2024-02-12",
    totalPrice: 120,
    status: "pending",
  },

  // Product 2 - Laptop bookings
  {
    id: "3",
    productId: "2",
    userId: "4",
    startDate: "2024-02-03",
    endDate: "2024-02-08",
    totalPrice: 250,
    status: "confirmed",
  },
  {
    id: "4",
    productId: "2",
    userId: "5",
    startDate: "2024-02-15",
    endDate: "2024-02-18",
    totalPrice: 150,
    status: "cancelled",
  },

  // Product 3 - Drill bookings
  {
    id: "5",
    productId: "3",
    userId: "6",
    startDate: "2024-02-02",
    endDate: "2024-02-04",
    totalPrice: 45,
    status: "completed",
  },
  {
    id: "6",
    productId: "3",
    userId: "7",
    startDate: "2024-02-14",
    endDate: "2024-02-16",
    totalPrice: 45,
    status: "confirmed",
  },

  // Product 4 - Tent bookings
  {
    id: "7",
    productId: "4",
    userId: "8",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    totalPrice: 60,
    status: "confirmed",
  },
  {
    id: "8",
    productId: "4",
    userId: "9",
    startDate: "2024-02-20",
    endDate: "2024-02-23",
    totalPrice: 90,
    status: "pending",
  },

  // Product 5 - Books bookings
  {
    id: "9",
    productId: "5",
    userId: "10",
    startDate: "2024-02-01",
    endDate: "2024-02-14",
    totalPrice: 35,
    status: "confirmed",
  },
  {
    id: "10",
    productId: "5",
    userId: "11",
    startDate: "2024-02-16",
    endDate: "2024-02-23",
    totalPrice: 35,
    status: "confirmed",
  },

  // Product 6 - Bike bookings
  {
    id: "11",
    productId: "6",
    userId: "12",
    startDate: "2024-02-04",
    endDate: "2024-02-06",
    totalPrice: 60,
    status: "completed",
  },
  {
    id: "12",
    productId: "6",
    userId: "13",
    startDate: "2024-02-11",
    endDate: "2024-02-13",
    totalPrice: 60,
    status: "confirmed",
  },

  // Product 7 - Projector bookings
  {
    id: "13",
    productId: "7",
    userId: "14",
    startDate: "2024-02-07",
    endDate: "2024-02-09",
    totalPrice: 90,
    status: "confirmed",
  },
  {
    id: "14",
    productId: "7",
    userId: "15",
    startDate: "2024-02-18",
    endDate: "2024-02-20",
    totalPrice: 90,
    status: "pending",
  },

  // Product 8 - Suitcase bookings
  {
    id: "15",
    productId: "8",
    userId: "16",
    startDate: "2024-02-08",
    endDate: "2024-02-12",
    totalPrice: 80,
    status: "confirmed",
  },
  {
    id: "16",
    productId: "8",
    userId: "17",
    startDate: "2024-02-19",
    endDate: "2024-02-22",
    totalPrice: 60,
    status: "confirmed",
  },

  // Product 9 - Guitar bookings
  {
    id: "17",
    productId: "9",
    userId: "18",
    startDate: "2024-02-09",
    endDate: "2024-02-16",
    totalPrice: 175,
    status: "confirmed",
  },
  {
    id: "18",
    productId: "9",
    userId: "19",
    startDate: "2024-02-21",
    endDate: "2024-02-23",
    totalPrice: 50,
    status: "pending",
  },

  // Product 10 - Drone bookings
  {
    id: "19",
    productId: "10",
    userId: "20",
    startDate: "2024-02-10",
    endDate: "2024-02-12",
    totalPrice: 180,
    status: "confirmed",
  },
  {
    id: "20",
    productId: "10",
    userId: "21",
    startDate: "2024-02-17",
    endDate: "2024-02-19",
    totalPrice: 180,
    status: "cancelled",
  },
];
